name: speech-emotion
channels:
  - defaults
dependencies:
  - python=3.8
  - pip
  - pip:
      - torch
      - torchvision
      - torchaudio
      - librosa
      - scikit-learn
      - matplotlib
      - numpy
      - transformers